{% set name = "github-copilot-sdk" %}
{% set version = "0.1.19" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/github_copilot_sdk-{{ version }}.tar.gz
  sha256: 2bba9db1ee0b3b6ff751568489777224e381c15427e253f98731c01a936833c2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=45
    - wheel
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - python-dateutil >=2.9.0.post0
    - pydantic >=2.0
    - typing_extensions >=4.0.0

test:
  imports:
    - copilot
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/github/copilot-sdk
  summary: Python SDK for GitHub Copilot CLI
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - akrherz
